---
title: "Initial Biome Composition Analysis"
author: "Timothy Brennhofer"
date: "June 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/Timothy Brennhofer/Desktop/KBS REU/KBS Data", echo = TRUE, warning = TRUE)

#set working directory
require(knitr)
opts_knit$set(root.dir = "C:/Users/Timothy Brennhofer/Desktop/KBS REU/KBS Data") #I'm not familiar with this approach
setwd("C:/Users/Timothy Brennhofer/Desktop/KBS REU/KBS Data") #not sure but the spaces ('white spaces') may be messing it up. Or, you may want to add a '\' to the end of the directory. But it's fine just to refer to the file directories directly. 
getwd()

#load necessary packages -- "library" or "require"
require(tidyverse) #this includes ggplot and dplyr - no need to load them separately
require(data.table)


#load data
abun_raw <- fread("C:/Users/Timothy Brennhofer/Desktop/KBS REU/KBS Data/2016_10_13_run2_otus.csv")
abun <- abun_raw
abun[345,4719] <- 0
abun <- abun %>%
  select(-Run, -Day, -Reads) %>%
  rename(Cage = `Cage#`) %>%
  gather(otu, abun, -SampleID, -Cage, - Abx, -Dose, -Hour, -Cohoused, -Pair) %>%
  group_by(SampleID) %>%
  mutate(abun = abun/sum(abun), otu = as.numeric(otu)) %>%
  mutate(mouseid = paste(Cage, Abx, sep = "_")) %>%
  ungroup()

```


```{r adding taxonomy}

#Load taxonomical data
tax <- fread("C:/Users/Timothy Brennhofer/Desktop/KBS REU/KBS Data/otus_table_joined_taxa.txt")

#Organize tax data into traditional classifications
tax <- tax %>%
  rename(otu = `#OTU ID`, tax = taxonomy) %>%
  mutate(tax = gsub("\\s|.__|\\[|\\]|Other", "", tax)) %>%
  separate(tax, sep = ';', c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), fill = 'right')
tax <- as.data.frame(apply(tax, 2, function(x) ifelse(x == '', 'unclassified', x)), stringsAsFactors = FALSE)
tax$otu <- as.numeric(tax$otu)

#Join taxonomical data and abundance data
abun_tax <- left_join(abun, tax, by = 'otu')

```

```{r intital composition data}

#Filter for inital reads and organize by phyla
#why alter abun_tax permanently?
abun_tax <- abun_tax %>%
  filter(Hour == 0) %>%
  group_by(mouseid, Phylum)

#Create graph to demonstrate initial compositions
tempz <- abun_tax %>%
  group_by(mouseid, Phylum) %>%
  filter(abun > .00001) %>%
  mutate(percentabun = paste0(round(100 *abun, 4), "%"))
  
#Note that this won't do anything; ggplot will plot things alphabetically unless you format the column as a "factor" (google it)
tempz <- tempz[order(mouseid, Phylum),]

ggplot(tempz, aes(x = mouseid, y = percentabun, fill = Phylum)) +
  geom_bar(stat = "identity")

#the problem here is that the paste0() function fills the "percentabun"column with "character" values, as opposed to "number" values. Thus, ggplot doesn't know how to plot character-based data in a quantitative way. Why not just:

ggplot(abun_tax, aes(x = mouseid, y = abun, fill = Phylum)) +
  geom_bar(stat = "identity")

```

