---
title: "Mouse_Microbiome"
author: "Tim"
date: "5/25/2018"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE)
#set working directory
setwd("/Users/sgamoney/Google Drive/mouse_microbiome/Mouse_Microbiome")

#load necessary packages -- "library" or "require"
require(tidyverse)
require(data.table)

#load data
abun_raw <- fread("2016_10_13_run2_otus.csv")
abun <- abun_raw
abun[345,4719] <- 0
abun <- abun %>%
  select(-Run, -Day, -Reads) %>%
  rename(Cage = `Cage#`) %>%
  gather(otuid, abun, -SampleID, -Cage, - Abx, -Dose, -Hour, -Cohoused, -Pair) %>%
  group_by(SampleID) %>%
  mutate(abun = abun/sum(abun))
```

Okay, now we'll learn to make *plots*!

```{r demo plot}
#demo plots
tempz <- abun %>%
  group_by(otuid, Hour) %>%
  summarise(abun = sum(abun)) %>%
  group_by(otuid) %>%
  mutate(total = sum(abun)) %>%
  filter(total > 7)

ggplot(tempz, aes(x = Hour, y = abun, color = otuid)) +
  geom_point() +
  stat_smooth() +
  facet_wrap(~otuid, scale = 'free_y')
```

```{r initial mouse mortality}

#set working directory
setwd("/Users/sgamoney/Google Drive/mouse_microbiome/Mouse_Microbiome")

#load necessary packages -- "library" or "require"
require(tidyverse)
require(data.table)

#load and set data
raw_abun <- fread("2016_10_13_run2_otus.csv")
new_abun <- raw_abun
new_abun[345,4719] <- 0
new_abun <- new_abun %>%
  select(-Run, -Day, -Reads) %>%
  rename(Cage = `Cage#`) %>%
  gather(otuid, abun, -SampleID, -Cage, -Abx, -Dose, -Hour, -Cohoused, -Pair) %>%
  group_by(SampleID) %>%
  mutate(abun = abun/sum(abun)) %>%
  mutate(mouseid = paste(Cage, Abx, sep = "_"))

#Filter time before 120 Hours and assign one of three mortality codes 
new_abun <- new_abun %>%
  filter(Hour < 121) %>%
  group_by(mouseid, otuid) %>%
  summarise(
    mstatus = ifelse(sum(abun) == 0, "absent", 
                     ifelse(abun[Hour == 120] > 0, "persistent", "leaves"))) 
```
